[tool.ruff]
line-length = 100
exclude = [
  ".git",
  ".ipynb_checkpoints",
  ".pyenv",
  ".ruff_cache",
  ".venv",
  ".vscode",
  ".python-version",
  "docs",
  "jacob",
]

[tool.ruff.format]
quote-style = "single"
